// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>
#include "arduino_secrets.h"

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onResetBoardChange();

String msg_log;
bool reset_board;

void initProperties(){

  ArduinoCloud.addProperty(msg_log, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(reset_board, READWRITE, ON_CHANGE, onResetBoardChange);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
